In [1]:
# Let import NumPy
import numpy as np

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

# Numpy Arrays

NumPy arrays will be the main concept that we will be using in this course. These arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type 

In [2]:
# Lets create a Python list. 
my_list = [-1,0,1]
my_list, type(my_list)

([-1, 0, 1], list)

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [3]:
my_array = np.array(my_list) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [4]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [6]:
np.arange(0,10) # similar to range() in Python, not including 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# We can give the step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [10]:
# start from 1 & end at 15 with 10 evenly spaced points b/w 1 to 15.
np.linspace(1, 15, 15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [37]:
# Lets find the step size with "retstep" which returns the array and the step size
my_linspace = np.linspace(0, 19.9999999,13, retstep=True)
my_linspace
# my_linspace[1] to get the stepsize only

(array([ 0.        ,  1.66666666,  3.33333332,  4.99999997,  6.66666663,
         8.33333329,  9.99999995, 11.66666661, 13.33333327, 14.99999992,
        16.66666658, 18.33333324, 19.9999999 ]), 1.6666666583333332)

In [11]:
np.linspace(1,15,30) # 1-D array 

array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
        3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
        5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
        8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
       10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
       13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ])

## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

### `zeros()`

* We want to create an array with **all zeros**<br>

*Press shift+tab for the documentation.*

In [12]:
np.zeros(3) # 1-D with 3 elements

array([0., 0., 0.])

In [13]:
np.zeros((4,6)) #(no_row, no_col) passing a tuple

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### `ones()`

* We want to create an array with **all ones**<br>

*Press shift+tab for the documentation.*

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((4,6)) #(no_row, no_col) passing a tuple

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## `eye()` 
Creates an identity matrix must be a square matrix, which is useful in several linear algebra problems.
* Return a 2-D array with **ones on the diagonal and zeros elsewhere.**

*Press shift+tab for the documentation.*

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
np.random.rand(3) # 1-D array with three elements

array([0.39059651, 0.46442725, 0.6177152 ])

In [18]:
np.random.rand(3,2) # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.11646242, 0.54623527],
       [0.4718328 , 0.15447893],
       [0.70650585, 0.48109287]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [19]:
np.random.randn(2)

array([-1.25486173,  0.21262454])

In [40]:
np.random.randn(4,4) # no tuple, each dimension as a separate argument

array([[-2.10296731e-01, -7.50912924e-01,  1.95594654e-01,
        -8.38349345e-01],
       [-1.73753828e-03, -2.04581822e+00,  6.04591446e-01,
         5.41982003e-01],
       [ 1.50670344e+00, -1.64390009e+00, -9.79229484e-01,
        -1.05464875e+00],
       [-1.34643449e+00,  7.50801001e-01, -1.36336742e+00,
        -2.01010774e-01]])

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [21]:
np.random.randint(1,100) #returns one random int, 1 inclusive, 100 exclusive

8

In [22]:
np.random.randint(1,100,10) #returns ten random int,

array([79, 11, 28, 56, 44, 58, 31, 63, 26,  7])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [23]:
# lets create 2 arrays using arange() and randint()
array_arange = np.arange(16)
array_ranint = np.random.randint(0,100,10)

In [24]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
array_ranint

array([94, 12, 65, 38, 64, 30, 32, 98, 67,  2])

#### `Reshape()`
Returns an array containing the same data with a new shape.

In [26]:
array_arange.reshape(8,2) # any other num will give error

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [27]:
array_ranint

array([94, 12, 65, 38, 64, 30, 32, 98, 67,  2])

In [28]:
array_ranint.max()

98

In [29]:
array_ranint.min()

2

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [30]:
array_ranint.argmax() # index starts from 0 . max by index at the array

7

In [31]:
array_ranint.argmin() # same as above

9

### Attributes
* `size, shape, dtype` 

In [32]:
# Lets take vector array, array_arange 
array_arange.shape

(16,)

In [33]:
# Size of the array 
array_arange.size

16

In [34]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [35]:
# Notice the two sets of brackets
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
array_arange.reshape(4,4).shape

(4, 4)

In [37]:
array_arange.reshape(16,1).shape

(16, 1)

In [38]:
array_arange.reshape(1,16).shape

(1, 16)

In [39]:
# What is the data type of the object in the array?
array_arange.dtype

dtype('int32')