In [9]:
# 1
# import numpy
import numpy as np

In [34]:
# 2
# crate numpy arrray like [1,2,...,30] and cast to python regular list
list = np.arange(1,31).tolist()
type(list)

list

In [37]:
# 3
# cast the list back to numpy array
list = np.array(list)
type(list)

numpy.ndarray

In [40]:
# 4
list.shape = (6,5)
list

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [67]:
# 5
i = 0
sum = 0
for row in list:
    j = 0
    for val in row:
        if i == j:
            sum = sum + val
        j = j + 1
    i = i + 1
sum

65

In [68]:
# 6
np.sum(list[1])

40

In [69]:
# 7
list_ones = np.ones((6,5), dtype=int)
list_ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [70]:
# 8
list + list_ones

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31]])

In [103]:
# 9
mat3 = np.random.randint(100, size = (30,30))
mat3

array([[52, 30, 19, 54,  0, 70, 89, 57, 15, 26, 86, 35, 14, 48, 11, 45,
        44,  9, 93, 77, 95, 47, 29, 84, 36, 46, 16, 60, 98,  2],
       [40, 68, 61, 60, 22, 41, 61, 42, 60, 22, 93, 57, 56, 92, 22, 91,
        21, 90, 37, 50, 50, 58,  5, 21, 54,  6,  9, 39, 19, 47],
       [49,  8, 62, 66, 96, 10, 73, 13, 72, 15, 51, 61, 48, 49, 17,  5,
        54, 27, 30, 63, 54, 20, 91, 12,  7,  1, 82, 84, 65, 44],
       [78,  5, 17, 47, 62, 78, 66, 31, 25, 55, 33, 75, 23, 52, 13, 11,
         8, 92, 67, 55, 50, 28,  3, 84, 25, 79, 83, 90, 59,  5],
       [13, 35, 35, 64, 41, 79, 43, 32, 77, 61, 66,  2, 60, 93,  7,  1,
        15, 65, 74, 93, 93, 42, 92, 46, 46, 98, 42, 90, 59, 41],
       [66, 59, 98, 26, 84, 18, 39, 72, 37, 48, 74,  1, 24,  8, 59, 57,
        60,  1, 85, 67, 75, 17, 62, 43, 85,  3, 60, 74, 35,  3],
       [43, 40, 90, 80, 56, 34, 45, 71, 38, 43, 29, 40, 55, 43, 35, 75,
        14, 22,  7, 91, 13, 68, 69, 70, 20, 90, 37, 27,  0, 38],
       [56, 49, 87, 25, 47, 79, 89, 67, 9

In [113]:
# 10
minimum = np.min(mat3)
print("min: ", minimum)

indexes = []
i = 0
sum = 0
for row in mat3:
    j = 0
    for val in row:
        if val == minimum:
            print("index of the minimum value is line ", i, "is ", j)
        j = j + 1
    i = i + 1
indexes

min:  0
index of the minimum value is line  0 is  4
index of the minimum value is line  6 is  28
index of the minimum value is line  15 is  19
index of the minimum value is line  16 is  12
index of the minimum value is line  29 is  16


[]

In [115]:
# 11
mat3[10:20,10:20]

array([[ 2, 91, 26,  4, 26, 33, 95, 33, 95, 43],
       [93, 16,  9, 24, 51, 49, 26, 48, 66, 79],
       [27, 52, 60, 91, 89, 71, 42, 57, 31, 64],
       [ 3, 71, 27, 89, 27, 64, 12, 32, 47, 78],
       [ 1, 16, 99, 56, 95, 78, 96, 76,  7, 97],
       [ 2, 65, 42, 25, 69, 12, 28, 43, 69,  0],
       [ 3, 68,  0,  2, 43, 36, 17, 61, 28, 83],
       [47, 33, 70, 65, 80, 12, 48, 51, 13, 50],
       [99, 22, 99, 63, 12, 81,  4, 97, 90, 31],
       [45, 43, 38, 99, 66,  3, 27, 54, 30, 45]])

In [117]:
# 12
print("mean: ", np.mean(mat3))
print("median: ", np.median(mat3))
print("std: ", np.std(mat3))

mean:  50.74666666666667
median:  51.0
std:  27.673096441610337


In [132]:
# 13
np.linspace(0,20,12,endpoint=False)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ,
       16.66666667, 18.33333333])