<a href='http://www.scienceacademy.ca'> <img style="float: left;height:70px" src="Logo_SA.png"></a>

# NumPy Essentials Exercises Overview:

**Good Luck**<br>


**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
# vector is a number of coordinates in space that every number is a value in different axis (every axis is dimension),
# for example we have the vector v = (1,2,3) in R^3 field [(x,y,z)],
# and the point (vector) is 1 in x axis, 2 in y axis and 3 in z axis.
# the use of vector is mostly in math and physic, use for exploring points in space, build graphcal engines and more,
# in python language vectors are used in data type called taple (for example - v = (1,2,3))

# matrix is an algebric tool use for the most to slove linear equations and to check attributes of vector (for example linear dependence)
# in computer science we using matrices for store data like tables (for the most) or storing vectors and more,
# in python language (and more others programming languages) to use matrices we used two dimension (or more) arrays (list in python),

# the basic math of vectors and matrices most commonly found in the field of linear algebra.

**2. How to import `NumPy` library?** 

In [4]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [6]:
list_1 = [1,2,3,4,5]

In [7]:
arr = np.asarray(list_1)
arr, type(arr)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [8]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [40]:
o = np.ones(5)
print(o)

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [12]:
np.full(5,10.)

array([10., 10., 10., 10., 10.])

array([ 10.,  10.,  10.,  10.,  10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [13]:
np.arange(52,100,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [14]:
np.linspace(0,1,10, retstep=True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [15]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
v = np.arange(0,25)
v.shape = (5,5)
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [23]:
np.linspace(0.1,2.5,25).reshape(5,5)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[ 0.1,  0.2,  0.3,  0.4,  0.5],
       [ 0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5],
       [ 1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [24]:
m = np.linspace(0,24,25)
m.shape = (5,5)
print(m, "\nStep size is: 1.0")

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]] 
Step size is: 1.0


[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]]
Step size is:  1.0


**14. What is the main difference between `linspace()` and `arange()`?**

In [31]:
# linspace() allows you to define how many values you get including the specified min and max value.
# arange() allows you to define the stepsize and infers the number of steps.
# both linspace() and arange() create numpy arrays

**15. How to generate a single random number using NumPy built-in function?**

In [25]:
np.random.rand(1)

array([0.29272307])

array([ 0.55509608])

**16. Write a code to generate a 7x5 matrix of 35 random numbers?** <br>
*Notice, there are no ( ) in the output matrix!*

In [41]:
r = np.random.rand(7,5)
print(r)

[[0.6861912  0.71487894 0.74735282 0.53102541 0.86489953]
 [0.98432302 0.907565   0.11633696 0.08706274 0.41524483]
 [0.39928567 0.01338294 0.42890412 0.18052706 0.34567547]
 [0.76040128 0.40987999 0.19240074 0.05076068 0.37846608]
 [0.45798297 0.54210549 0.63751689 0.87233267 0.6335079 ]
 [0.71604217 0.96371882 0.43420004 0.76694861 0.49977216]
 [0.07581559 0.76637828 0.92308207 0.33883896 0.07155481]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [27]:
b = np.identity(5)
np.fill_diagonal(b, 5)
b

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[ 5.,  0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

**18. Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [28]:
array_2d = np.arange(0,30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [29]:
array_2d[3:6,2:5]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [30]:
array_2d[5,4]

29

29

In [31]:
array_2d[0:3,1:2]

array([[ 1],
       [ 6],
       [11]])

array([[ 1],
       [ 6],
       [11]])

In [32]:
array_2d[2:3]

array([[10, 11, 12, 13, 14]])

array([10, 11, 12, 13, 14])

In [33]:
array_2d[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**19. Can you calculate the sum of all the numbers in array_2d?**

In [34]:
sum(sum(array_2d))

435

435

**20. Calculate sum of all the rows and columns in array_2d.**

In [42]:
rowsSum = sum(np.rot90(array_2d))
columsSum = sum(array_2d)
print("Row sum: ", rowsSum, "\nColums sum: ", columsSum)

Row sum:  [ 10  35  60  85 110 135] 
Colums sum:  [75 81 87 93 99]


Row sum: [ 10  35  60  85 110 135]
Columns sum: [75 81 87 93 99]


**21. Calculate the standard deviation of the values in array_2d.**

In [36]:
np.std(array_2d) 

8.65544144839919

8.6554414483991895

**22. Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [37]:
array_mask_2d = 0 != array_2d % 3
array_2d[array_mask_2d]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])